version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
      timezone: "Europe/Helsinki"
    groups:
      all:
        patterns:
          - "*"
